name: vendx
description: "Discover and buy products from local stores near you."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  go_router: ^14.6.1
  shared_preferences: ^2.0.6
  provider: ^6.1.2

  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.1
  qr_flutter: ^4.0.0
  smooth_page_indicator: ^1.2.0+3

  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  get: ^4.6.5
  get_storage: ^2.1.1

  flutter_stripe: ^11.3.0
  shimmer: ^2.0.0

  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/
